### ISSUE TITLE
VI runs in wrong bitness of LabVIEW if it is already open

### ISSUE THREAD

**Issue by chrisb2244** [JamesMc86/G-CLI#125] opened 2022-08-01 06:45 UTC
I _think_ this is probably undesirable, but it looks like all of the `vi.lib/G CLI Tools/...` paths are searched, regardless of bitness flag (i.e. `--x64` or nothing).

This resulted in output like the following (having installed `3.0.0-alpha.2` for LV2019-32bit only, with 2019-64 and 2021-32 also installed but without updated G-CLI:
```
PS C:\Users\Christian> g-cli --x64 -v  echo.vi -- hi
06:35:36.923 [DEBUG] G CLI Started - Verbose Mode
06:35:36.924 [DEBUG] Version 3.0.0-alpha.2
06:35:36.924 [DEBUG] G CLI Arguments: "C:\Program Files\G-CLI\bin\g-cli.exe" "--x64" "-v" "echo.vi" "--" "hi"
06:35:36.924 [DEBUG] Arguments passed to LabVIEW: "hi"
06:35:36.924 [DEBUG] Detected LabVIEW versions:
2019 SP1 f5, 32bit (C:\Program Files (x86)\National Instruments\LabVIEW 2019\)
2019 SP1 f5, 64bit (C:\Program Files\National Instruments\LabVIEW 2019\)
2021, 32bit (C:\Program Files (x86)\National Instruments\LabVIEW 2021\)

06:35:36.926 [DEBUG] Looks like VI "echo.vi" doesn't exist - Checking in vi.lib/G CLI Tools instead.
06:35:38.955 [DEBUG] Launching: C:\Program Files (x86)\National Instruments\LabVIEW 2021\LabVIEW.exe "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2021\\vi.lib\\G CLI Tools\\echo.vi -unattended -- -p:51684"
06:35:38.976 [DEBUG] Process launched with PID 14384
hi
06:35:45.177 [DEBUG] Comms reader stopped.
06:35:45.287 [DEBUG] Signal Handler Stopped.
06:35:45.287 [DEBUG] Action loop stopped.
06:35:45.288 [DEBUG] Waiting on monitoring thread to complete
06:35:45.446 [DEBUG] Monitoring complete and kill not requested.
06:35:45.446 [DEBUG] Stopping LabVIEW monitoring due to stop command from application
06:35:45.447 [DEBUG] Monitoring thread completed
06:35:45.447 [DEBUG] Exiting G-CLI with exit code 0
```

I initially observed the same behaviour in G-CLI v2.4, but figured I'd check if the Rust rewrite changed the behaviour.

I don't mind either way the 32-bit vi.lib being searched (although I expect it would cause the VI to be recompiled for changed bitness) but I'm definitely surprised that given no `--lv-ver` flag, but with `--x64`, a 32-bit version was chosen 😨 

I've never noticed this before, but unfortunately I don't have the `--verbose` flag on my CI setup, and when I see failures it's almost always on the 64-bit versions and succeeds if repeated (so I just wrapped it in a loop to retry, figuring it was some odd caching issue - oops, lazy...), so maybe it was related? (only a guess, might be completely unrelated, and I don't remember details).
My CI setup also passes an absolute path for the VI to run (it isn't in the Tools directory) so if it's a search issue, that would also prevent it I guess.

Opening this issue to let you know, if I get a bit more time I'll try figure out where it's falling through, but don't want to forget (plus you might immediately know the issue).

**Comment by chrisb2244** [comment] 2022-08-01 06:53
With G-CLI installed (i.e. the Tools dir) for both 32- and 64-bit LabVIEW 2019, and setting `--lv-ver 2019`, the behaviour seems as expected if they're closed before running the command.

If they're open already, then it seems like sometimes the wrong version is chosen, which then leads to this kind of output:
(3 calls, --x64, not, --x64 then getting confused and running in 32-bit, despite choosing the correct path).
```
PS C:\Users\Christian> g-cli --lv-ver 2019 --x64  -v echo.vi -- hi
06:50:06.196 [DEBUG] G CLI Started - Verbose Mode
06:50:06.196 [DEBUG] Version 3.0.0-alpha.2
06:50:06.196 [DEBUG] G CLI Arguments: "C:\Program Files\G-CLI\bin\g-cli.exe" "--lv-ver" "2019" "--x64" "-v" "echo.vi" "--" "hi"
06:50:06.196 [DEBUG] Arguments passed to LabVIEW: "hi"
06:50:06.197 [DEBUG] Detected LabVIEW versions:
2019 SP1 f5, 32bit (C:\Program Files (x86)\National Instruments\LabVIEW 2019\)
2019 SP1 f5, 64bit (C:\Program Files\National Instruments\LabVIEW 2019\)
2021, 32bit (C:\Program Files (x86)\National Instruments\LabVIEW 2021\)

06:50:06.198 [DEBUG] Looks like VI "echo.vi" doesn't exist - Checking in vi.lib/G CLI Tools instead.
06:50:08.238 [DEBUG] Launching: C:\Program Files\National Instruments\LabVIEW 2019\LabVIEW.exe "C:\\Program Files\\National Instruments\\LabVIEW 2019\\vi.lib\\G CLI Tools\\echo.vi -unattended -- -p:52056"
06:50:08.254 [DEBUG] Process launched with PID 19780
06:50:13.251 [DEBUG] Comms reader stopped.
hi
06:50:13.361 [DEBUG] Signal Handler Stopped.
06:50:13.361 [DEBUG] Action loop stopped.
06:50:13.362 [DEBUG] Waiting on monitoring thread to complete
06:50:13.597 [DEBUG] Monitoring complete and kill not requested.
06:50:13.598 [DEBUG] Stopping LabVIEW monitoring due to stop command from application
06:50:13.599 [DEBUG] Monitoring thread completed
06:50:13.599 [DEBUG] Exiting G-CLI with exit code 0
PS C:\Users\Christian> g-cli --lv-ver 2019  -v echo.vi -- hi
06:51:26.743 [DEBUG] G CLI Started - Verbose Mode
06:51:26.743 [DEBUG] Version 3.0.0-alpha.2
06:51:26.743 [DEBUG] G CLI Arguments: "C:\Program Files\G-CLI\bin\g-cli.exe" "--lv-ver" "2019" "-v" "echo.vi" "--" "hi"
06:51:26.744 [DEBUG] Arguments passed to LabVIEW: "hi"
06:51:26.746 [DEBUG] Detected LabVIEW versions:
2019 SP1 f5, 32bit (C:\Program Files (x86)\National Instruments\LabVIEW 2019\)
2019 SP1 f5, 64bit (C:\Program Files\National Instruments\LabVIEW 2019\)
2021, 32bit (C:\Program Files (x86)\National Instruments\LabVIEW 2021\)

06:51:26.746 [DEBUG] Looks like VI "echo.vi" doesn't exist - Checking in vi.lib/G CLI Tools instead.
06:51:28.803 [DEBUG] Launching: C:\Program Files (x86)\National Instruments\LabVIEW 2019\LabVIEW.exe "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2019\\vi.lib\\G CLI Tools\\echo.vi -unattended -- -p:52100"
06:51:28.830 [DEBUG] Process launched with PID 19204
06:51:34.261 [DEBUG] Comms reader stopped.
hi
06:51:34.371 [DEBUG] Signal Handler Stopped.
06:51:34.372 [DEBUG] Action loop stopped.
06:51:34.374 [DEBUG] Waiting on monitoring thread to complete
06:51:35.305 [DEBUG] Monitoring complete and kill not requested.
06:51:35.306 [DEBUG] Stopping LabVIEW monitoring due to stop command from application
06:51:35.307 [DEBUG] Monitoring thread completed
06:51:35.308 [DEBUG] Exiting G-CLI with exit code 0
PS C:\Users\Christian> g-cli --lv-ver 2019 --x64  -v echo.vi -- hi
06:51:45.162 [DEBUG] G CLI Started - Verbose Mode
06:51:45.162 [DEBUG] Version 3.0.0-alpha.2
06:51:45.163 [DEBUG] G CLI Arguments: "C:\Program Files\G-CLI\bin\g-cli.exe" "--lv-ver" "2019" "--x64" "-v" "echo.vi" "--" "hi"
06:51:45.163 [DEBUG] Arguments passed to LabVIEW: "hi"
06:51:45.165 [DEBUG] Detected LabVIEW versions:
2019 SP1 f5, 32bit (C:\Program Files (x86)\National Instruments\LabVIEW 2019\)
2019 SP1 f5, 64bit (C:\Program Files\National Instruments\LabVIEW 2019\)
2021, 32bit (C:\Program Files (x86)\National Instruments\LabVIEW 2021\)

06:51:45.165 [DEBUG] Looks like VI "echo.vi" doesn't exist - Checking in vi.lib/G CLI Tools instead.
06:51:47.237 [DEBUG] Launching: C:\Program Files\National Instruments\LabVIEW 2019\LabVIEW.exe "C:\\Program Files\\National Instruments\\LabVIEW 2019\\vi.lib\\G CLI Tools\\echo.vi -unattended -- -p:52132"
06:51:47.263 [DEBUG] Process launched with PID 17728
06:51:48.527 [INFO] Process lost + found at PID 19780
Error: No connection established with application.

Caused by:
    Timed out waiting for app to connect to g-cli

Location:
    src\main.rs:62:10
```

**Comment by JamesMc86** [comment] 2022-08-01 09:52
Yep - I have this exact issues on one of my systems and I've not yet been able to track down the correct behaviour. I've tried watching the system calls for VI package manager as that must avoid this issue somehow but I've not yet seen a way to force this.

I'm just going to tweak the title to match the end problem.

**Comment by chrisb2244** [comment] 2022-08-02 08:08
The last call (about 8 lines from the end of the log above) makes me think this might be a LabVIEW/NI problem, rather than a G-CLI problem (which sucks, because a G-CLI problem could probably be fixed...)

G-CLI clearly tries to run the 64-bit version of LabVIEW, (`[DEBUG] Launching: C:\Program Files\National Instruments\LabVIEW 2019\LabVIEW.exe "C:\\Program Files\\National Instruments\\LabVIEW 2019\\vi.lib\\G CLI Tools\\echo.vi -unattended -- -p:52132"`) but that VI executed in the open 32-bit version (iirc, both were open).

It looks like (I don't know any Rust, so maybe/maybe not) if the combination of version and bitness can't be matched, you take the default version, but I'd guess that if version isn't specified, bitness is ignored? And perhaps also that if you can't find matching version+bitness, then you take default version, regardless of either can be matched otherwise.

I don't know what I'd suggest as the better behaviour, but perhaps if one or both of `--lv-ver` or `--x64` are passed, don't use the default in the case of not being able to match?

All of that being said, in the logs above, the debug-listed path seems reasonable... so it isn't the cause of this problem?

**Comment by JamesMc86** [comment] 2022-08-04 14:44
Seen this just launching from the command line directly so looks like a LabVIEW issue.

Even worst it isn't very consistent in how it behaves so smells more like a bug. Will report to NI and see where we might be able to get to.

**Comment by JamesMc86** [comment] 2022-08-04 15:25
I see the same thing you commented on - the issue seems to be if they are both open it will just launch in the last one opened.

I have a feeling I've seen this before if there are multiple versions of LabVIEW. They are obviously doing some kind of registration and the last one wins somehow

**Comment by chrisb2244** [comment] 2022-08-04 15:33
My current planned solution is to avoid the situation with Docker containers (I'm looking forward to your GDevCon presentation), but it seems more than irritating that LabVIEW is willing to not do what it's told like this.

Is there some possibility it's a Windows related issue (perhaps based on file associations or something).

I've never seriously tried LabVIEW on Mac or Linux, so I can't say if the same happens there or not, but perhaps with your new G-CLI you or someone else could test it (I can try for Linux via VM if it helps, but I don't have a Mac available really).

**Comment by JamesMc86** [comment] 2022-08-04 15:37
For the curious:

I did some tracing with Process Monitor of the launch. It doesn't show how it decides to switch to the last opened version but basically every launch, LabVIEW writes to the registry keys that control launching from Windows Explorer. (HKCU\SOFTWARE\Classes\LabVIEWInstrument for example)

This also refers to ddeexec which seems to be a way for explorer to communicate with already open programs to load files. That tells it to use the application "LabVIEW". I'm guessing this is looked up by the new launch, finds an application that is open called LabVIEW (even though it is a different version) and sends it to that. ([This](https://docs.microsoft.com/en-us/windows/win32/shell/how-to-associate-verbs-with-dde-commands) suggests it is done by EXE name, hence the conflict)

I'm not hopeful for a fix to be honest - but definitely going to push for it reported as a bug - although I suspect I'm not the first to report it.

**Comment by JamesMc86** [comment] 2022-08-24 16:02
I'm afraid this is confirmed as a bug by LabVIEW R&D but with no great workaround. We need to either:

1. Close LabVIEW when finished and hope two jobs don't overlap.
2. Use AllowMultipleInstances in the INI files and launch then exit LabVIEW on each job.

Going to close this for now as there is nothing I can do.

**Closed by JamesMc86** 2022-08-24 16:02 UTC

**Comment by chrisb2244** [comment] 2022-08-24 16:05
Did they indicate they plan to do anything with it? Or this is wont-fix for NI too?

**Comment by JamesMc86** [comment] 2022-08-26 09:57
No indication really. It will get filed in their bug tracking and get put on the list I guess! Just waiting on the ID so we can at least register an interest in it with the relevant people.
