### ISSUE TITLE
 Unable to write data to the transport connection

### ISSUE THREAD

**Issue by mac671** [JamesMc86/G-CLI#87] opened 2020-02-25 11:57 UTC
I've installed g-cli 2.2.06.

I was using labview.cli 1.4.0.7 before it worked fine with my LV 2019 but had issues in x64 bit so I thought i'd update to see if I can get the x64 bit to work as well.

Now neither 64 bit or 32 bit work, and I get the following command line output.

```
Unhandled Exception: System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at G_CLI.Program.Main(String[] args)
```

I'm not sure what ports are closed ... and what does g-cli require.

All my previous commands to labview-cli get translated into g-cli so basically nothing works at the moment, any tips on troubleshooting this would help.

**Comment by JamesMc86** [comment] 2020-02-25 12:35
Hello,

Can you show the full output of running G CLI in verbose mode (-v flag) to try and understand at what stage this happens.

The big different between 1.0 and 2.0 is that 2.0 uses the NI service locator in order to manage the ports it uses. Therefore it needs to talk to port 3580 on localhost. It then uses a free port in the same way as 1.x for the new connection.

Do you have anything that could be blocking port 3580 locally? Can you try with any firewall or security software disabled temporarily to see if that clears it?

**Comment by mac671** [comment] 2020-02-25 16:52
Hi James,

Thanks for the quick reply.

I ran netstat -ab and here is what I see:
  TCP    0.0.0.0:3580           DESKTOP-XXXXXX:0      LISTENING
 [nisvcloc.exe]

Looks to me like port 3580 is open. And the service is listening on the mentioned port.

I've added --v to the command line I'm running but I got nothing more in the command line output beyond the .NET exception I've put in the opening post shows up in the verbose log. As if the --v flag changed nothing. As far as I can tell, LabVIEW 2019 pops up, opens up the VI I'm trying to call and then the exception happens.

I might look into this a bit more later but to get by right now I've reverted to 1.4.0.7 CLI and will work with the 32 bit version of LabVIEW just to get by today.

But I'd be interested in having my development environment setup to run the latest version of CLI in 64 bit as well.

**Comment by JamesMc86** [comment] 2020-02-25 17:39
If LabVIEW is launching that is a good sign.

That is strange about verbose mode - try just -v (though not sure why it wouldn't work with both)

It is harder to roll back but there is a name change in LabVIEW that needs mass compiling when going to G-CLI - check https://github.com/JamesMc86/G-CLI/wiki/Migrating-from-LabVIEW-CLI-to-G-CLI-(Name-Change) and make sure the VIs load if you open them directly.

**Comment by ShoutangYang** [comment] 2020-03-04 08:06
Hi,James,

Now I have the same problem  , look forward to how to solve.

**Comment by mac671** [comment] 2020-03-04 15:37
Hey,
I ended up reverting back to 1.4.0.7 of the original LabVIEW-CLI and am using 32bit for my project.

So I don't have a solution. And I might not have any time to play with this this week to see if I can get it to work. 

@ShoutangYang did you verify that in your case the port that James had mentioned 3580 is open? 
Can you send in the command line output with the -v command? Maybe this will help James troubleshoot.

I still have the VM where this is happening on ... so I can probably replicate the issue if I get some time next week.

Thanks,
Maciej

**Comment by JamesMc86** [comment] 2020-03-09 09:32
Hi @ShoutangYang 

As @mac671 says please run with -v and provide the output so I can see when this happens. 

If you are running through a CI server please also try running the command manually so you can see what LabVIEW does - I suspect this could be related to a crash or network issue on the LabVIEW side but I'm not sure yet.

**Comment by mac671** [comment] 2020-04-21 15:07
@JamesMc86 

Hi James I originally thought this issue was limited to my machine. But we wanted to update our build server.

We updated LabVIEW-CLI 1.4.0.7 to G-CLI 2.3.0.7 and we're seeing the same issue here is the command line output:

```
C:\Users\jenkins>g-cli -v --lv-ver 2019 --kill "C:\Users\Public\Documents\LabVIEW Data\Composed-CI\Source\CLI API\Call Build.vi" -- "-f C:\jenkins\workspace\Kineteks\ECT Line\ect-line-robot-control\Build Config\composed-ci.json" "-d C:\jenkins\workspace\Kineteks\ECT Line\ect-line-robot-control"
G CLI Started - Verbose Mode
Version 2.3.0.6 64-Bit
G CLI Arguments: -v --lv-ver 2019 --kill C:\Users\Public\Documents\LabVIEW Data\Composed-CI\Source\CLI API\Call Build.vi
Arguments passed to LabVIEW: -f C:\jenkins\workspace\Kineteks\ECT Line\ect-line-robot-control\Build Config\composed-ci.json -d C:\jenkins\workspace\Kineteks\ECT Line\ect-line-robot-control
Current Version: 2017 SP1 f3, 32bit
Detected LabVIEW versions:
2017 SP1 f3, 32bit(C:\Program Files (x86)\National Instruments\LabVIEW 2017\)
2018 SP1 f4, 32bit(C:\Program Files (x86)\National Instruments\LabVIEW 2018\)
2019 f2, 32bit(C:\Program Files (x86)\National Instruments\LabVIEW 2019\)
2017 SP1 f3, 64bit(C:\Program Files\National Instruments\LabVIEW 2017\)
2018 SP1 f4, 64bit(C:\Program Files\National Instruments\LabVIEW 2018\)
2019 f2, 64bit(C:\Program Files\National Instruments\LabVIEW 2019\)
Launching Program:
C:\Program Files (x86)\National Instruments\LabVIEW 2019\LabVIEW.exe "C:\Users\Public\Documents\LabVIEW Data\Composed-CI\Source\CLI API\Call Build.vi" -unattended -- -p:51520
LabVIEW/App started, process ID is 8984
Waiting for connection on port 51520
Client Connected
Unhandled Exception: System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at G_CLI.Program.Main(String[] args)
```

I would appreciate suggestions on how we can get this to work.

**Comment by JamesMc86** [comment] 2020-04-22 07:13
Hi @mac671 

Thanks for the verbose output. This shows that the connection is being established from LabVIEW so there is no firewall/blocking issue.

This means that the connection is dropping once it has been connected. Very interesting is that it is happening on a Write - the only time we currently write to LabVIEW is on launch to transfer the arguments so this means that very soon after connection LabVIEW is closing it.

Can you confirm:
* LabVIEW is staying open and seems to be doing something useful.
* You can open the VI you are calling and it seems to be valid. In particular the name change did require some changes which might explain the issue - Make sure you have changed the selection of the vis as described in https://github.com/JamesMc86/G-CLI/wiki/Migrating-from-LabVIEW-CLI-to-G-CLI-(Name-Change)
* Does LabVIEW report any errors - since this seems to be in the connect phase you may get an error out of the connect function.
* Put a 10s wait after connecting to G CLI. If I'm write this will still fail fast.
* Run another command - `g-cli -v --lv-ver 2019 --kill echo -- one two three` and see if the same thing happens.
* Try without the kill flag - I don't think it is doing anything here as it would be reported on the command line but doesn't hurt to try.

Sorry to give you a bit of a laundry list but we need to narrow down the cause. I'm pretty hopeful it will end up being something fairly simple as I've not seen this reported anywhere before. The upgrade for the name change being my best bet actually.

**Comment by JamesMc86** [comment] 2020-12-16 14:16
Hi @mac671 

I'm just going through the list and see this is still here. I presume it is no longer a problem given the amount of time that has passed so I'm going to close this issue now. Let me know if that is wrong though.

**Closed by JamesMc86** 2020-12-16 14:16 UTC

**Comment by mac671** [comment] 2020-12-16 15:05
Although I don't know what fixed it, eventually the issue went away. I am not sure what fixed it though. We have made a few updates to the CLI and we are using the 2.0. version now.
