### ISSUE TITLE
Exception Found System.IO.IOException 

### ISSUE THREAD

**Issue by ansible42** [JamesMc86/G-CLI#104] opened 2021-05-19 14:35 UTC
![image](https://user-images.githubusercontent.com/5238787/118830911-30d64d00-b874-11eb-869f-35a140e5bdf1.png)
 
I get this about every 4th run of the runner.  I have been killing LabVIEW before each command and that seems to help. 

Mostly wondering if other folks are seeing the same thing.

**Comment by JamesMc86** [comment] 2021-09-22 10:31
This is the first time I've seen that specific error message I'm afraid.

Do you have the ability to see the LabVIEW UI when running? That might give some clues as the error suggests something is happening on the LabVIEW side that causes the problem.

**Comment by ansible42** [comment] 2021-09-22 13:43
Unfortunately because this is a runner I cannot see the labview UI, which may be part of the problem. The runner is a windows service running in the background, which I had to do some fun tricks (running the service with local admin permissions under my username) to get it to see the g-cli as a valid command.

**Comment by JamesMc86** [comment] 2022-07-22 15:45
I'm going to close this as the 3.0 rewrite will likely mean these details aren't relevant.

3.0 will provide better descriptions for network failures so if we still see occurances then they will explain more.

**Closed by JamesMc86** 2022-07-22 15:45 UTC

**Comment by chrisb2244** [comment] 2022-08-26 07:35
@ansible42, not sure if you still have this issue at all (or if you've tried the 3.0 alpha) but I can seemingly reliably reproduce this if I have a (LabVIEW) error in my running VI (that is, an error appears in an error cluster wire, not that the VI is broken).

I'm using 2.4.0.4 64-bit in these builds, but I have played a little with the 3.0 build - will be rebuilding my images with that to see if it fixes the issue for me. (The issue here being that I don't get to see the error that broke the build, and it initially looks like G-CLI has an issue when really it's my code that's doing something wrong).

Obviously the better solution is to find out why my build is broken (because I need to fix that too...) but if I run G-CLI interactively, I get the error number (from an added error constant, the same project just builds fine on my desktop) output by the Exit with Error Cluster VI instead of the error you had in your screenshot.

**Comment by ansible42** [comment] 2022-08-26 18:07
I'm not in that role anymore @evanjohnson710 took over my job as CI master. 

I can tell you that I'm fairly certain that I will be using G-CLI in my next role that I am starting on Monday. I'll let you know if I find anything.
